name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - feat/*
      - fix/*
      - refactor/*

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencires
        run: yarn install --frozen-lockfile

      - name: Check lint
        run: yarn lint

      - name: Build test
        run: yarn build
